application/routes.py
from datetime import datetime

from sqlalchemy import desc


from flask import Blueprint
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_user, login_required, current_user, logout_user
from markdown import markdown
from werkzeug.security import generate_password_hash, check_password_hash

from .forms import RegisterForm, LoginForm, CreatePostForm, CommentForm, EmailForm
from .utils import sanitize_html, admin_only, send_mail
from .models import db, User, BlogPost, Comment


main_bp = Blueprint('main_bp', __name__, template_folder='templates')


@main_bp.route("/about")
def about():
    return render_template("about.html")


@main_bp.route("/delete/comment/<int:comment_id>", methods=["GET", "POST"])
@login_required
def comment_delete(comment_id):
    comment = Comment.query.get(comment_id)
    post = comment.post
    if request.method == "POST":
        db.session.delete(comment)
        db.session.commit()
        return redirect(url_for("main_bp.post_detail", post_id=post.id))
    return render_template("comment_delete.html", comment_id=comment_id, post_id=post.id)


@main_bp.route("/contact", methods=["GET", "POST"])
def contact():
    form = EmailForm()
    if request.method == "POST":
        subject = form.subject.data
        sender = form.email.data
        content = form.message.data
        send_mail(subject, sender, content)
        return redirect(url_for("main_bp.contact"))
    return render_template("contact.html", form=form)


@main_bp.route('/')
def index():
    posts = BlogPost.query.order_by(BlogPost.date.desc()).all()
    return render_template("index.html", all_posts=posts)


@main_bp.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST" and form.validate():
        email = form.email.data
        password = form.password.data
        user = User.query.filter_by(email=email).first()
        if not user or not check_password_hash(user.password, password):
            flash("Invalid credentials: check email and/or password", "error")
            return redirect(url_for("main_bp.login"))
        else:
            user.authenticated = True
            db.session.add(user)
            db.session.commit()
            login_user(user, remember=True)
            return redirect(url_for("main_bp.index"))
    return render_template("login.html", form=form)


@main_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main_bp.index'))


@main_bp.route("/post/<int:post_id>", methods=["GET", "POST"])
def post_detail(post_id):
    requested_post = BlogPost.query.get(post_id)
    mkd = markdown(requested_post.body, extensions=['fenced_code', 'codehilite'])
    comments = Comment.query.all()
    form = CommentForm()
    if request.method == "POST":
        if not current_user.is_authenticated:
            flash("Must be logged in for this", "error")
            return redirect(url_for("main_bp.login"))
        new_comment = Comment(
            post=requested_post,
            author=current_user,
            text=sanitize_html(form.body.data)
        )
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for("main_bp.post_detail", post_id=requested_post.id))
    return render_template("post_detail.html", markdown=mkd, post=requested_post, comments=comments, form=form)


@main_bp.route("/delete/post/<int:post_id>", methods=["GET", "POST"])
@admin_only
def post_delete(post_id):
    post = BlogPost.query.get(post_id)
    if request.method == "POST":
        db.session.delete(post)
        db.session.commit()
        return redirect(url_for('main_bp.index'))
    return render_template("post_delete.html", post_id=post_id)


@main_bp.route("/post/new", methods=["GET", "POST"])
@admin_only
def post_create():
    form = CreatePostForm()
    if request.method == "POST":
        new_post = BlogPost(
            author=current_user,
            title=form.title.data,
            subtitle=form.subtitle.data,
            body=form.body.data,
            img_url=form.img_url.data,
            date=datetime.utcnow(),
        )
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('main_bp.index'))
    return render_template("post_create.html", form=form)


@main_bp.route("/edit-post/<int:post_id>", methods=["GET", "POST"])
@admin_only
def post_edit(post_id):
    post = BlogPost.query.get(post_id)
    edit_form = CreatePostForm(
        author=post.author.name,
        title=post.title,
        subtitle=post.subtitle,
        body=post.body,
        img_url=post.img_url,
    )
    if edit_form.validate_on_submit():
        post.title = edit_form.title.data
        post.subtitle = edit_form.subtitle.data
        post.img_url = edit_form.img_url.data
        post.author = post.author
        post.body = edit_form.body.data
        db.session.commit()
        return redirect(url_for("main_bp.post_detail", post_id=post.id))
    return render_template("post_create.html", form=edit_form, is_edit=True)


@main_bp.route('/register', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if request.method == "POST" and form.validate():
        email = form.email.data
        if User.query.filter_by(email=email).first() is not None:
            flash("A user with that email already exists. You can login below.", "error")
            return redirect(url_for("main_bp.login"))
        password = form.password.data
        password_hashed_salted = generate_password_hash(
            password,
            method="pbkdf2:sha256",
            salt_length=10,
        )
        new_user = User(
            name=form.name.data,
            email=email,
            password=password_hashed_salted,
        )
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        return redirect(url_for("main_bp.index"))
    return render_template("register.html", form=form)

application/templates/about.html
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({{ url_for('static', filename='img/twombly4.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is what I do.</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
	<p>
	Philosopher, programmer, software developer.
	Most comfortable with the Python ecosystem (Django, Flask), working knowledge of a few other technologies (C, JavaScript, Postgres, Linux, Git, Docker, Heroku). 
	</p>
      </div>
    </div>
  </div>

  <hr>
  {% include "footer.html" %}

application/templates/comment_delete.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{{ ckeditor.load_code_theme() }}

{% block content %}
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead"
    style="background-image: url('{{ url_for('static', filename='img/edit-bg.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Sure you want to delete?</h1>
            <!-- <span class="subheading">Think hard!</span> -->
          </div>
        </div>
      </div>
    </div>
  </header>

  <form class="delete-form" action="{{ url_for("main_bp.comment_delete", comment_id=comment_id) }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <button class="btn btn-danger" type="submit">Delete</button>
    <a class="btn btn-primary" href="{{ url_for("main_bp.post_detail", post_id=post_id) }}">Cancel</a>
  </form>

{% include "footer.html" %}
{% endblock %}

application/templates/contact.html
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/twombly5.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have no answers (but you can write anyway).</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
	<form class="form" role="form" method="POST">
	  <input type="hidden" name="csrf_token" value={{ csrf_token() }}>
	  <div class="input-field">
	    {{ wtf.form_field(form.name) }}
	    {{ wtf.form_field(form.email) }}
	    {{ wtf.form_field(form.subject) }}
	    {{ wtf.form_field(form.message, cols="35", rows="10") }}
	    {{ wtf.form_field(form.send, class_="btn btn-primary") }}
	  </div>
	</form>
      </div>
    </div>
  </div>

  {% include "footer.html" %}
  {% endblock %}

application/templates/footer.html
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://github.com/pi-sigma">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.linkedin.com/in/pschilly/">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.youtube.com/channel/UCa5GHkwaG5HOWoqqv2slqmA">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Paul Schilling 2022</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  <!-- Custom scripts for this template -->
  <script src="{{ url_for('static', filename='js/clean-blog.min.js')}}"></script>

</body>

</html>

application/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pyparazzo</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='css/clean-blog.css')}}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/pygments.css')}}" rel="stylesheet">

  {{ ckeditor.load() }}
  {{ ckeditor.load_code_theme() }}
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{url_for('main_bp.index')}}">Pyparazzo</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
	data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.index') }}">Home</a>
          </li>
        
	  {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.register') }}">Register</a>
          </li>
      
	  {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.logout') }}">Log Out</a>
          </li>
	  {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.about') }}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main_bp.contact') }}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

application/templates/index.html
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({{ url_for('static', filename='img/twombly1.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Pyparazzo</h1>
            <span class="subheading">Musings about Programming and Software Development</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in all_posts %}
        <div class="post-preview">
          <a href="{{ url_for('main_bp.post_detail', post_id=post.id) }}">
            <h2 class="post-title">
              {{post.title}}
            </h2>
            <h3 class="post-subtitle">
              {{post.subtitle}}
            </h3>
          </a>
	  <p class="post-meta">Posted by <a href="{{ url_for('main_bp.about') }}">{{post.author.name}}</a> on {{post.date.strftime("%m-%d-%Y")}} 
	    {% if current_user.id == 1 %}
            <a href="{{url_for('main_bp.post_delete', post_id=post.id) }}">✘</a>
	    {% endif %}
          </p>
        </div>
        <hr>
        {% endfor %}

	<!-- messages -->
	{% with messages = get_flashed_messages() %}
	  {% if messages %}
	    <ul class=flashes>
	    {% for message in messages %}
	      <p>{{ message }}</p>
	    {% endfor %}
	    </ul>
	  {% endif %}
	{% endwith %}

        <!-- New Post -->
	{% if current_user.id == 1 %}
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="{{url_for('main_bp.post_create')}}">Create New Post</a>
        </div>
	{% endif %}
      </div>
    </div>
  </div>
  <hr>

{% include "footer.html" %}

application/templates/login.html
{% include "header.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({{ url_for('static', filename='img/twombly2.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto testing">
          <div class="page-heading">
	    <h1>Log In</h1>
            <span class="subheading">Welcome Back!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">

      <div class="col-lg-8 col-md-10 mx-auto content">

	{% with messages = get_flashed_messages() %}
	  {% if messages %}
	    <ul class=flashes>
	    {% for message in messages %}
	      <p>{{ message }}</p>
	    {% endfor %}
	    </ul>
	  {% endif %}
	{% endwith %}

	<form class="form" method="POST" role="form" novalidate=True>
	  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
	  <div class="input-field">
	    {{ wtf.form_field(form.email) }}
	    {{ wtf.form_field(form.password) }}
	    {{ wtf.form_field(form.login, class_="btn btn-primary") }}
	  </div>
	</form>
      </div>
    </div>
  </div>


{% include "footer.html" %}
{% endblock %}

application/templates/post_create.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{{ ckeditor.load_code_theme() }}

{% block content %}
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/edit-bg.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            {% if is_edit: %}
            <h1>Edit Post</h1>
            {% else: %}
            <h1>New Post</h1>
            {% endif %}
            <span class="subheading">You're going to make a great blog post!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
	<form class="form" method="POST" role="form">
	  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
	  {{ wtf.form_field(form.title) }}
	  {{ wtf.form_field(form.subtitle) }}
	  {{ wtf.form_field(form.author) }}
	  {{ wtf.form_field(form.img_url) }}
	  {{ wtf.form_field(form.body, cols="35", rows="35") }}
	  {{ wtf.form_field(form.submit, class_="btn btn-primary") }}
	</form>
      </div>
    </div>
  </div>

{% include "footer.html" %}
{% endblock %}

application/templates/post_delete.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{{ ckeditor.load_code_theme() }}

{% block content %}
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead"
    style="background-image: url('{{ url_for('static', filename='img/edit-bg.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Sure you want to delete?</h1>
          </div>
        </div>
      </div>
    </div>
  </header>

  <form class="delete-form" action="{{ url_for("main_bp.post_delete", post_id=post_id) }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
    <button class="btn btn-danger" type="submit">Delete</button>
    <a class="btn btn-primary" href="{{ url_for("main_bp.index") }}">Cancel</a>
  </form>

{% include "footer.html" %}
{% endblock %}

application/templates/post_detail.html
{% import "bootstrap/wtf.html" as wtf %}
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{post.img_url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{post.title}}</h1>
            <h2 class="subheading">{{post.subtitle}}</h2>
            <span class="meta">Posted by
		    <a href="#-{{ url_for('main_bp.about') }}">{{post.author.name}}</a>
              on {{post.date.strftime("%m-%d-%Y")}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {{ markdown|safe }}
          <hr>
	  <div class="clearfix">
	  {% if current_user.id == 1 %}
	  <a class="btn btn-primary float-right"
	     href="{{url_for('main_bp.post_edit', post_id=post.id)}}">Edit Post</a>
	  {% endif %}
	  </div>

	  <!-- messages -->
	  {% with messages = get_flashed_messages() %}
	    {% if messages %}
	      <ul class=flashes>
	      {% for message in messages %}
		<p>{{ message }}</p>
	      {% endfor %}
	      </ul>
	    {% endif %}
	  {% endwith %}

	  <!-- New comment -->
	  {% if current_user.is_authenticated %}
	    {{ ckeditor.load() }}
	    {{ ckeditor.config(name='body') }}
	    <form class="form" method="POST" role="form">
	      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
	      {{ wtf.form_field(form.body) }}
	      {{ wtf.form_field(form.submit, class_="btn btn-primary") }}
	    </form>
	  {% endif %}

	  <!-- Comment list -->
          <div class="col-lg-8 col-md-10 mx-auto comment">
              <ul class="commentList">
		{% for comment in comments %}
		  {% if post == comment.post %}
                    <div class="commenterImage">
		      <img src="{{ comment.author.email | gravatar }}"/>
                    </div>
                    <div class="commentText">
		      <p>{{ comment.text|safe }}</p>

			{% if current_user.id == comment.author_id or current_user.id == 1 %}
			  <a href="{{url_for('main_bp.comment_delete', comment_id=comment.id) }}">✘</a>
			{% endif %}

		      <span class="date sub-text">{{ comment.author.name }}</span>
                    </div>
		  {% endif %}
		{% endfor %}
              </ul>
            </div>
          </div>
      </div>
    </div>
  </article>

  <hr>
{% include "footer.html" %}

application/templates/register.html
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({{ url_for('static', filename='img/twombly3.jpg') }})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Register</h1>
            <span class="subheading">Hello there!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
	<form class="form" method="POST" role="form" novalidate=True>
	  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
	  <div clas="input-field">
	    {{ wtf.form_field(form.name) }}
	    {{ wtf.form_field(form.email) }}
	    {{ wtf.form_field(form.password) }}
	    {{ wtf.form_field(form.password2) }}
	    {{ wtf.form_field(form.register, class_="btn btn-primary") }}
	  </div>
	</form>
      </div>
    </div>
  </div>

{% include "footer.html" %}
{% endblock %}